import { CMSSY_DELIVERY_OPERATIONS } from "@cmssy/core/internal";

export const DEFAULT_OPERATIONS_OUT = "cmssy/operations.graphql";

const OPERATION_NAME = /^\s*(?:query|mutation|subscription)\s+([A-Za-z_]\w*)/m;

export function operationNames(): string[] {
  return CMSSY_DELIVERY_OPERATIONS.map((operation) => {
    const match = OPERATION_NAME.exec(operation.document);
    if (!match?.[1]) {
      throw new Error(
        "cmssy: a delivery operation has no name - anonymous documents cannot be vendored",
      );
    }
    return match[1];
  });
}

export function generateOperationsFile(): string {
  const header = [
    "# Generated by `cmssy types`. Do not edit - it is rewritten on every run.",
    "#",
    "# The delivery reads the SDK itself performs, vendored so your codegen",
    "# types them like any other document. Point `documents` in codegen.ts at",
    "# this file. Need a different selection set? Write your own query, under",
    "# your own operation name - two documents cannot share one.",
    "",
  ].join("\n");

  const documents = CMSSY_DELIVERY_OPERATIONS.map(
    (operation) =>
      `# ${operation.purpose.replace(/\s+/g, " ").trim()}\n${operation.document}`,
  ).join("\n\n");

  return `${header}\n${documents}\n`;
}
