import { CMSSY_DELIVERY_OPERATIONS } from "@cmssy/core/internal";

export const DEFAULT_OPERATIONS_OUT = "cmssy/operations.graphql";

/**
 * The delivery operations, as a `.graphql` file the app's own codegen picks up.
 *
 * Vendored, not owned: the file is rewritten on every run, so editing it is
 * pointless rather than dangerous. An app that needs a different selection set
 * writes its own document under its own operation name - two documents sharing
 * one name is a hard error in graphql-codegen's client preset anyway, so
 * "edit the generated one" was never a workflow that worked.
 */
export function generateOperationsFile(): string {
  const header = [
    "# Generated by `cmssy types`. Do not edit - it is rewritten on every run.",
    "#",
    "# These are the delivery reads the SDK itself performs, vendored here so",
    "# your codegen types them like any other document. Need a different",
    "# selection set? Write your own query, under your own operation name.",
    "",
  ].join("\n");

  const documents = CMSSY_DELIVERY_OPERATIONS.map(
    (operation) => `# ${operation.purpose}\n${operation.document.trim()}`,
  ).join("\n\n");

  return `${header}\n${documents}\n`;
}

/** Operation names, for the "wrote N operations" line and for tests. */
export function operationNames(): string[] {
  return CMSSY_DELIVERY_OPERATIONS.map((operation) => operation.name);
}
